#!/usr/bin/env python3
"""
UDB Bundle Script — deterministic amalgamation of modular UDB sources.

Reads the canonical sources under src/ strictly read-only, inlines the public
header, the internal header, and the ordered udb_*.c.inc implementation units
referenced from src/udb.c, and produces dist/udb.c plus modules.list.

The generator never mutates its inputs and never invokes a code formatter.
Formatting is a separate, explicit step (scripts/format-sources) so that the
bundle output depends only on repository bytes.

Usage:
    python3 scripts/bundle.py          regenerate dist/udb.c and modules.list
    python3 scripts/bundle.py --check  read-only verification; exit 1 on drift
"""

import argparse
import hashlib
import os
import re
import sys

REPO_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(REPO_DIR, "src")
DIST_DIR = os.path.join(REPO_DIR, "dist")
OUT_C_FILE = os.path.join(DIST_DIR, "udb.c")
MODULES_LIST_FILE = os.path.join(REPO_DIR, "modules.list")

MODULE_MANAGER_HEADER = """/*
 * UDB 4 - Unreal Database System for UnrealIRCd 6
 * Subsystem: Standalone Bundled Distribution
 *
 * Author: David Abuín Fontán ('davidlig') <https://github.com/davidlig/unrealircd-udb>
 * Based on the original UDB concept by Trocotronic.
 *
 * (C) 2026 David Abuín Fontán
 * License: GNU General Public License v2+
 */

/*** <<<MODULE MANAGER START>>>
module
{
	documentation "https://github.com/davidlig/unrealircd-udb";
	troubleshooting "In case of problems, report issues at https://github.com/davidlig/unrealircd-udb/issues";
	min-unrealircd-version "6.2.*";
	post-install-text {
		"The UDB module is now installed. Next steps:";
		"1. Add the following to your unrealircd.conf:";
		"   loadmodule \\"third/udb\\";";
		"   udb {";
		"       propagator \\"ares-services.yourdomain.net\\";";
		"   };";
		"2. Verify configuration with: ./unrealircd configtest";
		"3. Restart UnrealIRCd: ./unrealircd restart";
	}
}
*** <<<MODULE MANAGER END>>>
*/
"""


def fail(message):
    print(f"ERROR: {message}", file=sys.stderr)
    raise SystemExit(1)


def read_source(path):
    with open(path, "r", encoding="utf-8") as handle:
        text = handle.read()
    if "\r" in text:
        fail(f"{path}: carriage returns are not allowed in canonical sources")
    return text


def replace_include(text, pattern, replacement, source):
    """Line-anchored include replacement; unmatched occurrences fail closed."""
    inline_regex = re.compile(rf'^([ \t]*)#include\s+{pattern}[ \t]*$', re.MULTILINE)
    matches = inline_regex.findall(text)
    if not matches:
        fail(f"{source}: expected include {pattern} was not found")
    return inline_regex.sub(lambda m: replacement, text)


def inline_unit(filename, stack, included):
    path = os.path.join(SRC_DIR, filename)
    if not os.path.isfile(path):
        fail(f"included unit not found: {filename}")
    if filename in stack:
        fail(f"cyclic include detected: {' -> '.join(stack + [filename])}")
    if filename in included:
        fail(f"unit included more than once: {filename}")
    included.add(filename)
    text = read_source(path)
    text = re.sub(r'^[ \t]*#include\s+"udb\.h"[ \t]*$', '', text, flags=re.MULTILINE)
    text = re.sub(
        r'^[ \t]*#include\s+"([^"]+\.c\.inc)"[ \t]*$',
        lambda m: f"/* Inlined: {m.group(1)} */\n" + inline_unit(m.group(1), stack + [filename], included) +
                  f"\n/* End of {m.group(1)} */",
        text,
        flags=re.MULTILINE,
    )
    return text


def build_bundle():
    udb_h = read_source(os.path.join(SRC_DIR, "udb.h"))
    udb_internal_h = read_source(os.path.join(SRC_DIR, "udb_internal.h"))
    udb_c = read_source(os.path.join(SRC_DIR, "udb.c"))

    # The bundle carries its own manager header; drop the entry banner of udb.c.
    clean_udb_c = re.sub(r'/\*.*?\*/', '', udb_c, count=1, flags=re.DOTALL).strip()

    udb_internal_h = replace_include(udb_internal_h, r'"udb\.h"', udb_h, "udb_internal.h")
    clean_udb_c = replace_include(clean_udb_c, r'"udb_internal\.h"', udb_internal_h, "udb.c")

    included = set()
    clean_udb_c = re.sub(
        r'^[ \t]*#include\s+"([^"]+\.c\.inc)"[ \t]*$',
        lambda m: f"/* Inlined: {m.group(1)} */\n" + inline_unit(m.group(1), ["udb.c"], included) +
                  f"\n/* End of {m.group(1)} */",
        clean_udb_c,
        flags=re.MULTILINE,
    )

    # Every implementation unit present in src/ must be referenced exactly once.
    on_disk = sorted(name for name in os.listdir(SRC_DIR) if name.endswith(".c.inc"))
    orphans = [name for name in on_disk if name not in included]
    if orphans:
        fail(f"unreferenced implementation units: {', '.join(orphans)}")

    bundled = MODULE_MANAGER_HEADER + "\n" + clean_udb_c + "\n"
    return bundled.encode("utf-8")


def build_modules_list(dist_bytes):
    sha256 = hashlib.sha256(dist_bytes).hexdigest()
    content = f"""/* Autogenerated UDB Module Repository Index for UnrealIRCd 6 */
module "third/udb"
{{
	description "UDB 4 (Unreal DataBase) distributed nick/channel/IP management & sync";
	version "4.0.0";
	author "David Abuín Fontán ('davidlig')";
	documentation "https://github.com/davidlig/unrealircd-udb";
	troubleshooting "In case of problems, report issues at https://github.com/davidlig/unrealircd-udb/issues";
	source "https://raw.githubusercontent.com/davidlig/unrealircd-udb/main/dist/udb.c";
	sha256sum "{sha256}";
	min-unrealircd-version "6.2.*";
	post-install-text
	{{
		"The UDB module is now installed. Next steps:";
		"1. Add the following to your unrealircd.conf:";
		"   loadmodule \\"third/udb\\";";
		"   udb {{";
		"       propagator \\"ares-services.yourdomain.net\\";";
		"   }};";
		"2. Verify configuration with: ./unrealircd configtest";
		"3. Restart UnrealIRCd: ./unrealircd restart";
	}}
}}
"""
    return content.encode("utf-8")


def atomic_write(path, payload):
    tmp_path = f"{path}.tmp"
    with open(tmp_path, "wb") as handle:
        handle.write(payload)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(tmp_path, path)


def main():
    parser = argparse.ArgumentParser(description="Deterministic UDB bundle generator")
    parser.add_argument("--check", action="store_true",
                        help="verify dist/udb.c and modules.list match the canonical sources; write nothing")
    args = parser.parse_args()

    dist_bytes = build_bundle()
    modules_bytes = build_modules_list(dist_bytes)

    if args.check:
        ok = True
        for path, expected in ((OUT_C_FILE, dist_bytes), (MODULES_LIST_FILE, modules_bytes)):
            try:
                with open(path, "rb") as handle:
                    current = handle.read()
            except FileNotFoundError:
                print(f"MISSING: {os.path.relpath(path, REPO_DIR)}")
                ok = False
                continue
            if current != expected:
                print(f"OUTDATED: {os.path.relpath(path, REPO_DIR)}")
                ok = False
        if not ok:
            print("Bundle drift detected; run: python3 scripts/bundle.py")
            return 1
        print(f"Bundle is up to date (sha256 {hashlib.sha256(dist_bytes).hexdigest()}).")
        return 0

    os.makedirs(DIST_DIR, exist_ok=True)
    atomic_write(OUT_C_FILE, dist_bytes)
    atomic_write(MODULES_LIST_FILE, modules_bytes)
    print(f"[+] Successfully bundled standalone C file -> {OUT_C_FILE}")
    print(f"[+] Generated repository index -> {MODULES_LIST_FILE} (SHA256: {hashlib.sha256(dist_bytes).hexdigest()})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
