#!/usr/bin/env python3
"""
UDB Bundle Script
Combines modular UDB sources (udb.c, udb.h, udb_internal.h, and ordered
udb_*.c.inc implementation units, including lifecycle coordination) into a
single, self-contained files/udb.c and generates modules.list for UnrealIRCd
Module Manager.
"""

import os
import re
import hashlib
import subprocess

REPO_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(REPO_DIR, "src")
DIST_DIR = os.path.join(REPO_DIR, "dist")
OUT_C_FILE = os.path.join(DIST_DIR, "udb.c")
MODULES_LIST_FILE = os.path.join(REPO_DIR, "modules.list")

MODULE_MANAGER_HEADER = """/*
 * UDB 4 - Unreal Database System for UnrealIRCd 6
 * Subsystem: Standalone Bundled Distribution
 *
 * Author: David Abuín Fontán ('davidlig') <https://github.com/davidlig/unrealircd-udb>
 * Based on the original UDB concept by Trocotronic.
 *
 * (C) 2026 David Abuín Fontán
 * License: GNU General Public License v2+
 */

/*** <<<MODULE MANAGER START>>>
module
{
	documentation "https://github.com/davidlig/unrealircd-udb";
	troubleshooting "In case of problems, report issues at https://github.com/davidlig/unrealircd-udb/issues";
	min-unrealircd-version "6.*";
	post-install-text {
		"The UDB module is now installed. Next steps:";
		"1. Add the following to your unrealircd.conf:";
		"   loadmodule \\"third/udb\\";";
		"   udb {";
		"       propagator \\"ares-services.yourdomain.net\\";";
		"   };";
		"2. Verify configuration with: ./unrealircd configtest";
		"3. Restart UnrealIRCd: ./unrealircd restart";
	}
}
*** <<<MODULE MANAGER END>>>
*/
"""

def format_sources():
    src_files = []
    for root, _, files in os.walk(SRC_DIR):
        for file in files:
            if file.endswith((".c", ".h", ".inc")):
                src_files.append(os.path.join(root, file))
    if src_files:
        subprocess.run(["clang-format", "-i"] + sorted(src_files), check=True)
        print(f"[+] Formatted {len(src_files)} source files in {SRC_DIR}")

def bundle_sources():
    format_sources()
    os.makedirs(DIST_DIR, exist_ok=True)
    
    # Read public and implementation-only headers.
    with open(os.path.join(SRC_DIR, "udb.h"), "r", encoding="utf-8") as f:
        udb_h_content = f.read()
    with open(os.path.join(SRC_DIR, "udb_internal.h"), "r", encoding="utf-8") as f:
        udb_internal_h_content = f.read()

    # Read udb.c
    with open(os.path.join(SRC_DIR, "udb.c"), "r", encoding="utf-8") as f:
        udb_c_content = f.read()

    # Remove initial multi-line comment from udb.c if any
    clean_udb_c = re.sub(r'/\*.*?\*/', '', udb_c_content, count=1, flags=re.DOTALL).strip()

    # Inline the public header into the internal header, then inline that
    # complete implementation interface into the one-file distribution.
    udb_internal_h_content = re.sub(
        r'#include\s+"udb\.h"', udb_h_content, udb_internal_h_content
    )
    clean_udb_c = re.sub(
        r'#include\s+"udb_internal\.h"', udb_internal_h_content, clean_udb_c
    )

    # Recursively inline implementation includes while preserving their order.
    def replace_inc(match):
        filename = match.group(1)
        inc_path = os.path.join(SRC_DIR, filename)
        if os.path.exists(inc_path):
            with open(inc_path, "r", encoding="utf-8") as inc_file:
                inc_text = inc_file.read()
                inc_text = re.sub(r'#include\s+"udb\.h"', '', inc_text)
                inc_text = re.sub(r'#include\s+"([^\"]+\.c\.inc)"', replace_inc, inc_text)
                return f"/* Inlined: {filename} */\n" + inc_text + f"\n/* End of {filename} */"
        else:
            raise FileNotFoundError(f"Included file not found: {inc_path}")

    bundled_code = re.sub(r'#include\s+"([^"]+\.c\.inc)"', replace_inc, clean_udb_c)

    full_output = MODULE_MANAGER_HEADER + "\n" + bundled_code

    with open(OUT_C_FILE, "w", encoding="utf-8") as f:
        f.write(full_output)

    subprocess.run(["clang-format", "-i", OUT_C_FILE], check=True)

    with open(OUT_C_FILE, "r", encoding="utf-8") as f:
        content = f.read()
    if not content.endswith("\n"):
        with open(OUT_C_FILE, "a", encoding="utf-8") as f:
            f.write("\n")

    print(f"[+] Successfully bundled standalone C file -> {OUT_C_FILE}")
    return OUT_C_FILE

def generate_modules_list(c_file_path):
    with open(c_file_path, "rb") as f:
        sha256 = hashlib.sha256(f.read()).hexdigest()

    modules_list_content = f"""/* Autogenerated UDB Module Repository Index for UnrealIRCd 6 */
module "third/udb"
{{
	description "UDB 4 (Unreal DataBase) distributed nick/channel/IP management & sync";
	version "4.0.0";
	author "David Abuín Fontán ('davidlig')";
	documentation "https://github.com/davidlig/unrealircd-udb";
	troubleshooting "In case of problems, report issues at https://github.com/davidlig/unrealircd-udb/issues";
	source "https://raw.githubusercontent.com/davidlig/unrealircd-udb/main/dist/udb.c";
	sha256sum "{sha256}";
	min-unrealircd-version "6.*";
	post-install-text
	{{
		"The UDB module is now installed. Next steps:";
		"1. Add the following to your unrealircd.conf:";
		"   loadmodule \\"third/udb\\";";
		"   udb {{";
		"       propagator \\"ares-services.yourdomain.net\\";";
		"   }};";
		"2. Verify configuration with: ./unrealircd configtest";
		"3. Restart UnrealIRCd: ./unrealircd restart";
	}}
}}
"""
    with open(MODULES_LIST_FILE, "w", encoding="utf-8") as f:
        f.write(modules_list_content)

    print(f"[+] Generated repository index -> {MODULES_LIST_FILE} (SHA256: {sha256})")

if __name__ == "__main__":
    c_path = bundle_sources()
    generate_modules_list(c_path)
